### ISSUE TITLE
[Improvement] use a more compact format for clojure data structures serialization

### ISSUE THREAD

**Issue by icamts** [klauswuestefeld/prevayler-clj#1]
Hi Klaus, first of all: thanks for Prevayler!
I've made this little test

``` clojure
(ns prevayler.core
  (:require
    [org.prevayler :refer :all])
  (:import
    [java.io File]))

(defn tmp-file [l]
  (doto
    (File/createTempFile (str "test-" l "-") ".tmp")
    (.delete)))

(let [handler-fn (fn [m [k v]] (assoc m k v))
      prev! #(prevayler! handler-fn %1 (tmp-file %2))
      initial-state (atom {})]
  (with-open [p (prev! @initial-state "a")]
    (doseq [kv (range 1000000)]
      (handle! p [(keyword (str "a" kv)) kv]))
    (reset! initial-state @p))
  (with-open [p (prev! @initial-state "b")]
    ))
```

the first temp file created contains a map and one milion two element clojure vectors and is 1GB in size. Clojure data structures are not so compact when persisted through Java serialization. I'd sugget to improve this using a clojure serialization library with fallback to java serialization, like ptaoussanis/nippy.

Cheers,
Luca

**Comment by klauswuestefeld** [comment]
Hi Luca,

What would the size be using nippy, for example?

On Wed, Aug 5, 2015 at 9:38 AM, icamts notifications@github.com wrote:

> Hi Klaus, first of all: thanks for Prevayler!
> I've made this little test
> 
> (ns prevayler.core
>   (:require
>     [org.prevayler :refer :all])
>   (:import
>     [java.io File]))
> 
> (defn tmp-file [l](doto
>     %28File/createTempFile %28str) ".tmp")
>     (.delete)))
> 
> (let [handler-fn (fn [m [k v]](assoc m k v))
>       prev! #(prevayler! handler-fn %1 (tmp-file %2))
>       initial-state (atom {})](with-open [p %28prev! @initial-state)]
>     (doseq [kv (range 1000000)](handle! p [%28keyword %28str "a" kv)) kv]))
>     (reset! initial-state @p))
>   (with-open [p (prev! @initial-state "b")]
>     ))
> 
> the first temp file created contains a map and one milion two element
> clojure vectors and is 1GB in size. Clojure data structures are not so
> compact when persisted through Java serialization. I'd sugget to improve
> this using a clojure serialization library with fallback to java
> serialization, like ptaoussanis/nippy.
> 
> Cheers,
> Luca
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/klauswuestefeld/prevayler-clj/issues/1.

## 

Valeu, Klaus.

**Comment by icamts** [comment]
Hi Klaus,
I've made this test with a simulated prevayler state

``` clojure
(ns nippy.core
  (:require [taoensso.nippy :as nippy]))

(def sim-state (cons {} (take 1000000 (iterate (fn [[k v]] [(keyword (str "c" (inc v))) (inc v)]) [:c0 0]))))

(def frozen-sim-state (nippy/freeze sim-state))

(count frozen-sim-state) ;;=> 8749428
```

nippy returns a byte array that is about 8MB.

**Comment by klauswuestefeld** [comment]
8MB vs 1GB?

**Comment by icamts** [comment]
I dont' know Clojure data structures internals but it seems the java serialization of the vector [:a1 1] is about 1kB, while nippy serialization is a few bytes.

This is my REPL session to further investigate this issue

``` clojure
user=> (class [:a1 1])
clojure.lang.PersistentVector

user=> (import [java.io ByteArrayOutputStream ObjectOutputStream])
java.io.ObjectOutputStream

user=> (def baos (ByteArrayOutputStream.))
#'user/baos

user=> (def oos (ObjectOutputStream. baos))
#'user/oos

user=> (.writeObject oos [:a1 1])
nil

user=> (.size baos)
671

user=> (.writeObject oos [:a1000000 1000000])
nil

user=> (.size baos) ;the first contains object definition, the second adds 85 bytes
756

user=> (.writeObject oos [:a1000000 1000000])
nil

user=> (.size baos)
813

user=> (def baos (ByteArrayOutputStream.))
#'user/baos

user=> (def oos (ObjectOutputStream. baos))
#'user/oos

user=> (.size baos)
4

user=> (def ss (cons {} (map #(vector (keyword (str "c" %)) %) (range 1000000))))
#'user/ss

user=> (take 10 ss)
({} [:c0 0] [:c1 1] [:c2 2] [:c3 3] [:c4 4] [:c5 5] [:c6 6] [:c7 7] [:c8 8])

user=> (last ss)
[:c999999 999999]

user=> (doseq [s ss] (.writeObject oos s))
nil

user=> (.size baos)
83889635

user=> (/ *1 1024 1024)
83889635/1048576

user=> (double *1)
80.00339031219482

user=> (.close oos)
nil

user=> (.close baos)
nil

user=> (.size baos)
83889635
```

A third result! Only 80MB. Is it possible prevayler is serializing object definition for every vector?
Please verify by your own the results of these tests. I'm pretty confused now.

**Comment by klauswuestefeld** [comment]
On Fri, Aug 7, 2015 at 7:19 AM, icamts notifications@github.com wrote:

> Is it possible prevayler is serializing object definition for every vector?

Yes. It does that the avoid leaks.

Klaus

**Comment by icamts** [comment]
Hi Klaus, which leaks do you refer to? My understanding of prevayler is that the logs file is read completely before the system is available.

Luca

**Comment by klauswuestefeld** [comment]
If we didnt call .reset on the object output stream, it would hold all
transactions in ram forever, We call .reset every transaction, so the class
names get serialized every transaction too. A good compromise would be to
call reset every 100 transactions or so.

**Comment by icamts** [comment]
Now it's clear. Thanks.

**Comment by ghost** [comment]
prevayler-clj version 3.0.0 is now using nippy! ;)
